<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
class B_ReceiptViewDetail extends ViewDetail
{
    public function display()
    {
        $account = $this->bean->receipt_product_name;
        $quantity1 =  $this->bean->receipt_product_quantity;
        $price1 = $this->bean->receipt_unit_price;
        $total_unit1 = $this->bean->receipt_product_total;

        $name = explode(":", $account);
        $quantity = explode(":", $quantity1);
        $price = explode(":", $price1);
        $total_unit = explode(":", $total_unit1);

        array_pop($name);
        array_pop($quantity);
        array_pop($price);
        array_pop($total_unit);

        $stt = array();

        for ($i = 0; $i < count($name); $i++) {
            $stt[$i][] = $i + 1;
            $stt[$i][] = $name[$i];
            $stt[$i][] = $price[$i];
            $stt[$i][] = $quantity[$i];
            $stt[$i][] = $total_unit[$i];
        }

        $this->ss->assign("total", $this->bean->receipt_original_price);
        $this->ss->assign("stt", $stt);
        parent::display(); // TODO: Change the autogenerated stub
    }
}

?>
