<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
class B_InvoiceViewDetail extends ViewDetail
{
    public function display()
    {
        //truyền giá trị của field ticker_symbol vào tpl
        $this->ss->assign("invoice_customer", $this->bean->invoice_customer);
        parent::display(); // TODO: Change the autogenerated stub
    }
}

?>
